### ISSUE TITLE
(IO Error) unsupported file type

### ISSUE THREAD

**Issue by liampauling** [tarb/betfair_data#7]
Although normally gzipped my raw files look like this:

> resources/PRO-1.170258213
   resources/1.170258213
   resources/170258213

I see in [handle_file](https://github.com/tarb/betfair_data/blob/a81ebb573f3384d62950e558117b075004aee9ae/src/files.rs#L117) it validates the extension. Not sure the 'Rust' way of doing things but can it auto detect file type or as a last resort read as per a text/json file?

**Comment by tarb** [comment]
Sure, seems fine to default no extension to assume plain text, they're not really .json files anyway because of the newline delimiter.

**Comment by tarb** [comment]
No extension paths should now be treated as plaintext, other (unsupported) extensions will still error though. Changed in [ab1abe6](https://github.com/tarb/betfair_data/commit/ab1abe62d62634661b6081660b8d3e2a959dd25b)

**Comment by liampauling** [comment]
Brilliant, will test this tomorrow

**Comment by liampauling** [comment]
I think I am having problems due to the code reading the marketId as an extension `170258213` in `resources/1.170258213`, can anything be done here? If not I can change my code to handle but I doubt I am the only one who saves the files in the same way with no extension.

**Comment by tarb** [comment]
Ok this was a pretty big (and in hindsight obvious) oversight on my end. I think this warrants a different approach, I'm thinking looking for MarketId "like" files with a simple regex and treat them also as plain text.

It's getting a little un-elegant but I guess thats life

**Comment by tarb** [comment]
Files should now handle files that suffix in the same format of a market id as plain text.
Or more specifically whose file name matches this regex ```^.*\d{1}\.\d{9}$```
eg
```data/1.123456789```
```data/Pro-1.123456789```

**Comment by liampauling** [comment]
All working on my side

**Comment by tarb** [comment]
Thanks for the help! Fixed in [5babe16](https://github.com/tarb/betfair_data/commit/5babe169ef625c193bec405580eaf04daaeb6e5e)
